import { staffProfileSchema } from "./staff.schema";

const rawStaffProfiles = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    slug: "avery-brooks",
    displayName: "Avery Brooks",
    age: 27,
    countryCode: "AU",
    avatar: "/images/about/dani.jpeg",
    photos: [
      { id: "avery-1", url: "/images/about/dani.jpeg", order: 0 },
      { id: "avery-2", url: "/images/events/event-07.jpg", order: 1 },
      { id: "avery-3", url: "/images/events/event-10.jpg", order: 2 },
    ],
    shortBio: "Warm, quick on her feet, and at home hosting private celebrations and brand events.",
    longBio: "Avery is an experienced event host who brings calm organisation and genuine energy to every room. She is equally comfortable welcoming guests, coordinating a run sheet, supporting a brand activation, or keeping a private celebration moving naturally.",
    location: "Sydney",
    roles: ["Party Host", "Brand Ambassador"],
    languages: ["English"],
    averageRating: 4.9,
    reviewCount: 28,
    reviews: [
      { id: "avery-review-1", rating: 5, comment: "Avery understood the brief immediately and made every guest feel welcome.", reviewerName: "Mia T", createdAt: "2026-06-12" },
      { id: "avery-review-2", rating: 5, comment: "Professional, social, and completely reliable from setup to finish.", reviewerName: "Daniel K", createdAt: "2026-04-21" },
    ],
    totalJobsWorked: 74,
    isAvailable: true,
    joinedAt: "2024-02-18",
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    slug: "maya-patel",
    displayName: "Maya Patel",
    age: 25,
    countryCode: "AU",
    avatar: "/images/about/molly.jpeg",
    photos: [
      { id: "maya-1", url: "/images/about/molly.jpeg", order: 0 },
      { id: "maya-2", url: "/images/events/event-09.jpg", order: 1 },
      { id: "maya-3", url: "/images/events/event-10.jpg", order: 2 },
    ],
    shortBio: "A polished bartender and host with a sharp eye for detail and an easy social style.",
    longBio: "Maya has worked across cocktail events, private dinners, and product launches. She enjoys fast-paced service, reads a room well, and keeps the guest experience polished without making it feel formal.",
    location: "Melbourne",
    roles: ["Event Bartender", "Event Host"],
    languages: ["English", "Hindi"],
    averageRating: 4.8,
    reviewCount: 19,
    reviews: [
      { id: "maya-review-1", rating: 5, comment: "Our bar ran smoothly all night and Maya was excellent with guests.", reviewerName: "Olivia R", createdAt: "2026-07-03" },
    ],
    totalJobsWorked: 51,
    isAvailable: true,
    joinedAt: "2024-08-02",
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    slug: "jordan-kim",
    displayName: "Jordan Kim",
    age: 29,
    countryCode: "AU",
    avatar: "/images/about/james.jpeg",
    photos: [
      { id: "jordan-1", url: "/images/about/james.jpeg", order: 0 },
      { id: "jordan-2", url: "/images/events/event-08.jpg", order: 1 },
      { id: "jordan-3", url: "/images/events/event-12.jpg", order: 2 },
    ],
    shortBio: "Open-format DJ and confident MC for private parties, launches, and late-night events.",
    longBio: "Jordan combines open-format DJ sets with confident microphone work. His sets move comfortably between laid-back arrivals, familiar party favourites, and high-energy dance floors, with preparation tailored to each client and venue.",
    location: "Gold Coast",
    roles: ["DJ", "MC"],
    languages: ["English", "Korean"],
    averageRating: 4.9,
    reviewCount: 34,
    reviews: [
      { id: "jordan-review-1", rating: 5, comment: "The dance floor stayed full and the transitions were exactly right for our crowd.", reviewerName: "Sophie W", createdAt: "2026-05-30" },
    ],
    totalJobsWorked: 96,
    isAvailable: false,
    joinedAt: "2023-11-10",
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    slug: "zoe-martin",
    displayName: "Zoe Martin",
    age: 24,
    countryCode: "AU",
    avatar: "/images/about/katrina.jpeg",
    photos: [
      { id: "zoe-1", url: "/images/about/katrina.jpeg", order: 0 },
      { id: "zoe-2", url: "/images/events/event-11.jpg", order: 1 },
      { id: "zoe-3", url: "/images/events/event-03.jpg", order: 2 },
    ],
    shortBio: "Friendly promotional talent who is confident with guests, products, and live activations.",
    longBio: "Zoe works across launches, trade events, registrations, and social activations. She is confident learning key messages, starting conversations, and representing a brand with a natural and approachable manner.",
    location: "Sydney",
    roles: ["Promotional Model", "Brand Ambassador"],
    languages: ["English", "French"],
    averageRating: 4.7,
    reviewCount: 16,
    reviews: [
      { id: "zoe-review-1", rating: 5, comment: "Engaging and prepared. Zoe represented the campaign beautifully.", reviewerName: "Grace L", createdAt: "2026-03-19" },
    ],
    totalJobsWorked: 43,
    isAvailable: true,
    joinedAt: "2025-01-14",
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    slug: "luca-bennett",
    displayName: "Luca Bennett",
    age: 31,
    countryCode: "AU",
    avatar: "/images/about/richard.png",
    photos: [
      { id: "luca-1", url: "/images/about/richard.png", order: 0 },
      { id: "luca-2", url: "/images/events/event-10.jpg", order: 1 },
      { id: "luca-3", url: "/images/events/event-09.jpg", order: 2 },
    ],
    shortBio: "Experienced cocktail bartender and floor lead for premium private and corporate events.",
    longBio: "Luca has led service teams for formal dinners, private homes, and large corporate functions. He is organised, composed under pressure, and known for keeping service standards consistent throughout an event.",
    location: "Brisbane",
    roles: ["Event Bartender", "Wait Staff"],
    languages: ["English", "Italian"],
    averageRating: 5,
    reviewCount: 41,
    reviews: [
      { id: "luca-review-1", rating: 5, comment: "Luca led the team exceptionally well and anticipated what we needed.", reviewerName: "Ethan P", createdAt: "2026-07-17" },
      { id: "luca-review-2", rating: 5, comment: "Excellent service and communication throughout the booking.", reviewerName: "Amelia S", createdAt: "2026-02-08" },
    ],
    totalJobsWorked: 128,
    isAvailable: true,
    joinedAt: "2023-05-26",
  },
  {
    id: "00000000-0000-4000-8000-000000000006",
    slug: "riley-stone",
    displayName: "Riley Stone",
    age: 30,
    countryCode: "AU",
    avatar: "/images/about/julian.jpeg",
    photos: [
      { id: "riley-1", url: "/images/about/julian.jpeg", order: 0 },
      { id: "riley-2", url: "/images/events/event-07.jpg", order: 1 },
      { id: "riley-3", url: "/images/events/event-11.jpg", order: 2 },
    ],
    shortBio: "A personable event host with strong hospitality experience and dependable floor presence.",
    longBio: "Riley brings a steady, guest-focused approach to private functions and outdoor events. He can support setup, guest arrivals, floor service, and pack-down while maintaining a relaxed and professional presence.",
    location: "Melbourne",
    roles: ["Party Host", "Wait Staff"],
    languages: ["English", "Spanish"],
    averageRating: 4.6,
    reviewCount: 12,
    reviews: [
      { id: "riley-review-1", rating: 5, comment: "Reliable, proactive, and genuinely good with every guest.", reviewerName: "Noah C", createdAt: "2026-04-11" },
    ],
    totalJobsWorked: 39,
    isAvailable: false,
    joinedAt: "2025-03-09",
  },
] as const;

export const staffFixtures = staffProfileSchema.array().parse(rawStaffProfiles);
